# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Build and upload a new build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"] || "DNRQX7V8X4",
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"] || "api_keys/AuthKey_DNRQX7V8X4.p8",
      in_house: false
    )

    increment_build_number(xcodeproj: "wallino-reader.xcodeproj")

    build_app(
      scheme: "Wallino Reader",
      xcodeproj: "wallino-reader.xcodeproj",
      export_method: "app-store",
      output_directory: "fastlane/build"
    )

    upload_to_testflight(api_key: api_key)
  end

  desc "Increment build number"
  lane :incrementbuildnumber do
    increment_build_number(xcodeproj: "wallino-reader.xcodeproj")
  end

  desc "Set version"
  lane :setversion do
    version = prompt(text: "Version ?")
    increment_version_number(version_number: version, xcodeproj: "wallino-reader.xcodeproj")
  end

  desc "Run tests"
  lane :test do
    run_tests(scheme: "Wallino Reader")
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Wallino Reader")
  end
end
