devices([
  "iPhone 17"
])

languages([
  "en-US",
  "de-DE",
  "es-ES",
  "fr-FR",
  "hr",
  "it",
  "ja",
  "nl-NL",
  "ru",
  "tr",
  "zh-Hans",
  "zh-Hant"
])

scheme("Wallino Reader")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(false)
